name: Cross Compile and Upload

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.1"

      - name: Build Linux
        run: |
          env GOOS=linux GOARCH=amd64
          go mod tidy && go build -o dist/linux-amd64/server server/server.go && go build -o dist/linux-amd64/client client/client.go
      - name: Build Windows
        run: |
          env GOOS=windows GOARCH=amd64
          go mod tidy && go build -o dist/windows-amd64/server.exe server/server.go && go build -o dist/windows-amd64/client.exe client/client.go
      - name: Build Darwin
        run: |
          env GOOS=darwin GOARCH=amd64
          go mod tidy && go build -o dist/darwin-amd64/server server/server.go && go build -o dist/darwin-amd64/client client/client.go
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.sha }}
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          files: |
            dist/linux-amd64/linux-amd64-server
            dist/linux-amd64/linux-amd64-client
            dist/windows-amd64/windows-amd64-server.exe
            dist/windows-amd64/windows-amd64-client.exe
            dist/darwin-amd64/darwin-amd64-server
            dist/darwin-amd64/darwin-amd64-client
